app:
  env: test
http:
  http_host: 127.0.0.1
  http_port: 8084
  read_timeout: 60s
  write_timeout: 60s
  run_mode: test #开发:debug,线上:release,测试:test

mysql:
  database: my_test
  username: root
  password: 123456
  host: 127.0.0.1
  port: 3306
  timeout: 5000ms
  charset: utf8mb4
  max_idle: 10
  max_open: 20
  run_mode: debug #开发测试:debug,线上prod

redis:
  network: tcp
  addr: 127.0.0.1:6379
  password:
  db: 0
  pool_size: 4
  min_idle_conns: 2
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  pool_timeout: 4s
  idle_check_frequency: 60s
  idle_timeout: 5m
  max_conn_age:
  max_retries: 1
  min_retry_backoff: 8ms
  max_retry_backoff: 512ms

kafka:
  addrs:
    - "127.0.0.1:9092"
    - "127.0.0.1:9093"
    - "127.0.0.1:9094"

upload:
  image_prefix_url: http://127.0.0.1:8083
  image_save_path: upload/images/
  image_max_size: 5242880 # 5*1024*1024
  image_allow_exts:
    - ".jpg"
    - ".jpeg"
    - ".png"
  runtime_root_path: runtime/

domain:
  user: #http://xxxxxx.com

wxapp:
  app_id:
  app_secret:

logger:
  max_size: 500
  max_age: 15
  atomic_level: debug
  file_path: runtime/log